linters:
  enable-all: true
  disable:
    # Deprecated
    - exportloopref
    - execinquery
    - gomnd
    # Too noisy or irrelevant
    - lll
    - funlen
    - gocognit
    - cyclop
linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com
          - gopkg.in
